//HintName: VerifyVectorize.MyExample/Lerp.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Lerp"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery LerpQuery(EntityStore _store, global::System.Numerics.Vector3 dst, global::System.Numerics.Vector3 amount, bool vectorized = true)
        {
            var _query = _Lerp_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var srcSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Lerp_Avx(srcSpan, dst, amount);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Lerp(ref srcSpan[n], dst, amount);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Lerp_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position3>
            _Lerp_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position3>)
                EntityStore.UserDataGet(_store, _Lerp_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position3>();

            EntityStore.UserDataSet(_store, _Lerp_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _Lerp_Avx(
            Span<global::VerifyVectorize.Position3> src,
            global::System.Numerics.Vector3 dst,
            global::System.Numerics.Vector3 amount)
        {
            int i = 0;
            var end = src.Length - 8;
            if (i > end) {
                return 0;
            }
            // --- Locals
            var dst_0 = Vector256.Create(dst.X, dst.Y, dst.Z, dst.X, dst.Y, dst.Z, dst.X, dst.Y);
            var dst_1 = Vector256.Create(dst.Z, dst.X, dst.Y, dst.Z, dst.X, dst.Y, dst.Z, dst.X);
            var dst_2 = Vector256.Create(dst.Y, dst.Z, dst.X, dst.Y, dst.Z, dst.X, dst.Y, dst.Z);

            var amount_0 = Vector256.Create(amount.X, amount.Y, amount.Z, amount.X, amount.Y, amount.Z, amount.X, amount.Y);
            var amount_1 = Vector256.Create(amount.Z, amount.X, amount.Y, amount.Z, amount.X, amount.Y, amount.Z, amount.X);
            var amount_2 = Vector256.Create(amount.Y, amount.Z, amount.X, amount.Y, amount.Z, amount.X, amount.Y, amount.Z);

            fixed (global::VerifyVectorize.Position3* src_first = src)
            {
                for (; i <= end; i += 8)
                {
                    float* src_ptr = (float*)(src_first + i);

                    // --- 1. Load
                    Vector256<float> src_0 = Avx.LoadVector256(src_ptr + 0);
                    Vector256<float> src_1 = Avx.LoadVector256(src_ptr + 8);
                    Vector256<float> src_2 = Avx.LoadVector256(src_ptr + 16);

                    // --- 2. Compute
                    position_0 = Fma.MultiplyAdd(amount_0, Avx.Subtract(dst_0, src_0), src_0);
                    position_1 = Fma.MultiplyAdd(amount_1, Avx.Subtract(dst_1, src_1), src_1);
                    position_2 = Fma.MultiplyAdd(amount_2, Avx.Subtract(dst_2, src_2), src_2);

                    // --- 3. Store
                    Avx.Store(position_ptr + 0, position_0);
                    Avx.Store(position_ptr + 8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
