//HintName: VerifyVectorize.MyExample/Multiply_Matrix4x4.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Multiply_Matrix4x4"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery Multiply_Matrix4x4Query(EntityStore _store, in global::System.Numerics.Matrix4x4 matrix)
        {
            var _query = _Multiply_Matrix4x4_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                for (; n < _entities.Length; n++) {
                    Multiply_Matrix4x4(ref positionSpan[n], in matrix);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Multiply_Matrix4x4_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position4>
            _Multiply_Matrix4x4_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position4>)
                EntityStore.UserDataGet(_store, _Multiply_Matrix4x4_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position4>();

            EntityStore.UserDataSet(_store, _Multiply_Matrix4x4_Slot, _query);
            return _query;
        }

    #endregion
    }
}
