//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, global::System.Numerics.Vector2 dst, float amount, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var srcSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(srcSpan, dst, amount);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(ref srcSpan[n], dst, amount);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position2>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position2>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position2>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(
            Span<global::VerifyVectorize.Position2> src,
            global::System.Numerics.Vector2 dst,
            float amount)
        {
            int i = 0;
            var end = src.Length - 16;
            if (i > end) {
                return 0;
            }
            Vector128<float> dst_half = Vector128.Create(dst.X, dst.Y, dst.X, dst.Y);
            var dst_0 = Avx.InsertVector128(dst_half.ToVector256(), dst_half, 1);
            var dst_1 = dst_0;
            var dst_2 = dst_0;
            var dst_3 = dst_0;

            var amount_scalar = Vector256.Create(amount);

            fixed (global::VerifyVectorize.Position2* src_first = src)
            {
                for (; i <= end; i += 16)
                {
                    float* src_ptr = (float*)(src_first + i);

                    // 1. Load
                    Vector256<float> src_0 = Avx.LoadVector256(src_ptr + 0);
                    Vector256<float> src_1 = Avx.LoadVector256(src_ptr + 8);
                    Vector256<float> src_2 = Avx.LoadVector256(src_ptr + 16);
                    Vector256<float> src_3 = Avx.LoadVector256(src_ptr + 24);

                    // 2. Compute
                    position_0 = Fma.MultiplyAdd(amount_scalar, Avx.Subtract(dst_0, src_0), src_0);
                    position_1 = Fma.MultiplyAdd(amount_scalar, Avx.Subtract(dst_1, src_1), src_1);
                    position_2 = Fma.MultiplyAdd(amount_scalar, Avx.Subtract(dst_2, src_2), src_2);
                    position_3 = Fma.MultiplyAdd(amount_scalar, Avx.Subtract(dst_3, src_3), src_3);

                    // 3. Store
                    Avx.Store(position_ptr + 0, position_0);
                    Avx.Store(position_ptr + 8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);


                }
            }
            return i;
        }

    #endregion
    }
}
