//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, ref global::System.Numerics.Vector2 sum, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(positionSpan, ref sum);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(positionSpan[n], ref sum);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position2>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position2>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position2>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(
            Span<global::VerifyVectorize.Position2> position,ref 
            global::System.Numerics.Vector2 sum)
        {
            int i = 0;
            var end = position.Length - 16;
            if (i > end) {
                return 0;
            }
            // --- Locals
            Vector128<float> sum_half = Vector128.Create(sum.X, sum.Y, sum.X, sum.Y);
            var sum_0 = Avx.InsertVector128(sum_half.ToVector256(), sum_half, 1);
            var sum_1 = sum_0;
            var sum_2 = sum_0;
            var sum_3 = sum_0;

            fixed (global::VerifyVectorize.Position2* position_first = position)
            {
                for (; i <= end; i += 16)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr + 0);
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr + 8);
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);

                    // --- 2. Compute
                    sum_0 = Avx.Add(sum_0, position_0);
                    sum_1 = Avx.Add(sum_1, position_1);
                    sum_2 = Avx.Add(sum_2, position_2);
                    sum_3 = Avx.Add(sum_3, position_3);

                    // --- 3. Store
                    Avx.Store(sum_ptr + 0, sum_0);
                    Avx.Store(sum_ptr + 8, sum_1);
                    Avx.Store(sum_ptr + 16, sum_2);
                    Avx.Store(sum_ptr + 24, sum_3);
                }
            }
            return i;
        }

    #endregion
    }
}
