//HintName: VerifyVectorize.MyExample/MoveExample.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="MoveExample"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery MoveExampleQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _MoveExample_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var velocitySpan = chunk.Chunk2.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                // if (Avx.IsSupported) {
                    n = _MoveExample_Avx();
                // }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    MoveExample(ref positionSpan[n], in velocitySpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _MoveExample_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::Friflo.Engine.ECS.Position, global::VerifyVectorize.Velocity> _MoveExample_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::Friflo.Engine.ECS.Position, global::VerifyVectorize.Velocity>)EntityStore.UserDataGet(_store, _MoveExample_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::Friflo.Engine.ECS.Position, global::VerifyVectorize.Velocity>();

            EntityStore.UserDataSet(_store, _MoveExample_Slot, _query);
            return _query;
        }

        private static unsafe int _MoveExample_Avx()
        {
            int i = 0;
            var end = 0; // position.Length - 8;
            for (; i <= end; i += 8)
            {
            }
            return i;
        }

    #endregion
    }
}
