//HintName: VerifyVectorize.MyExample/Access_static.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Access_static"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery Access_staticQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _Access_static_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var srcSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Access_static_Avx(srcSpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Access_static(ref srcSpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Access_static_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position3>
            _Access_static_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position3>)
                EntityStore.UserDataGet(_store, _Access_static_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position3>();

            EntityStore.UserDataSet(_store, _Access_static_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _Access_static_Avx(
            Span<global::VerifyVectorize.Position3> src)
        {
            int i = 0;
            var end = src.Length - 8;
            if (i > end) {
                return 0;
            }
            // --- Locals
            var const0 = System.Numerics.Vector3.Pi; // static
            var const0_0 = Vector256.Create(const0.X, const0.Y, const0.Z, const0.X, const0.Y, const0.Z, const0.X, const0.Y);
            var const0_1 = Vector256.Create(const0.Z, const0.X, const0.Y, const0.Z, const0.X, const0.Y, const0.Z, const0.X);
            var const0_2 = Vector256.Create(const0.Y, const0.Z, const0.X, const0.Y, const0.Z, const0.X, const0.Y, const0.Z);

            fixed (global::VerifyVectorize.Position3* src_first = src)
            {
                for (; i <= end; i += 8)
                {
                    float* src_ptr = (float*)(src_first + i);

                    // --- 1. Load
                    Vector256<float> src_0 = Avx.LoadVector256(src_ptr + 0);
                    Vector256<float> src_1 = Avx.LoadVector256(src_ptr + 8);
                    Vector256<float> src_2 = Avx.LoadVector256(src_ptr + 16);

                    // --- 2. Compute
                    position_0 = const0_0;
                    position_1 = const0_1;
                    position_2 = const0_2;

                    // --- 3. Store
                    Avx.Store(position_ptr + 0, position_0);
                    Avx.Store(position_ptr + 8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
