//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, global::System.Numerics.Vector2 min, global::System.Numerics.Vector2 max, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(positionSpan, min, max);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(ref positionSpan[n], min, max);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position2>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position2>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position2>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(
            Span<global::VerifyVectorize.Position2> position,
            global::System.Numerics.Vector2 min,
            global::System.Numerics.Vector2 max)
        {
            int i = 0;
            var end = position.Length - 16;
            if (i > end) {
                return 0;
            }
            Vector128<float> min_half = Vector128.Create(min.X, min.Y, min.X, min.Y);
            var min_0 = Avx.InsertVector128(min_half.ToVector256(), min_half, 1);
            var min_1 = min_0;
            var min_2 = min_0;
            var min_3 = min_0;
            Vector128<float> max_half = Vector128.Create(max.X, max.Y, max.X, max.Y);
            var max_0 = Avx.InsertVector128(max_half.ToVector256(), max_half, 1);
            var max_1 = max_0;
            var max_2 = max_0;
            var max_3 = max_0;

            fixed (global::VerifyVectorize.Position2* position_first = position)
            {
                for (; i <= end; i += 16)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr + 0);
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr + 8);
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);

                    // 2. Compute
                    position_0 = Avx.Min(max_0, Avx.Max(min_0, position_0));
                    position_1 = Avx.Min(max_1, Avx.Max(min_1, position_1));
                    position_2 = Avx.Min(max_2, Avx.Max(min_2, position_2));
                    position_3 = Avx.Min(max_3, Avx.Max(min_3, position_3));

                    // 3. Store
                    Avx.Store(position_ptr + 0, position_0);
                    Avx.Store(position_ptr + 8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);


                }
            }
            return i;
        }

    #endregion
    }
}
