//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var factorSpan = chunk.Chunk2.Span;
                var factor2Span = chunk.Chunk3.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(positionSpan, factorSpan, factor2Span);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(positionSpan[n], ref factorSpan[n], factor2Span[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position2, global::VerifyVectorize.FloatComponent, global::VerifyVectorize.FloatComponent2>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position2, global::VerifyVectorize.FloatComponent, global::VerifyVectorize.FloatComponent2>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position2, global::VerifyVectorize.FloatComponent, global::VerifyVectorize.FloatComponent2>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(
            Span<global::VerifyVectorize.Position2> position,
            Span<global::VerifyVectorize.FloatComponent> factor,
            Span<global::VerifyVectorize.FloatComponent2> factor2)
        {
            int i = 0;
            var end = position.Length - 16;
            if (i > end) {
                return 0;
            }
            // --- Locals
            Vector256<int> factor_mask_lo = Vector256.Create( 0, 0, 1, 1, 2, 2, 3, 3);
            Vector256<int> factor_mask_hi = Vector256.Create( 4, 4, 5, 5, 6, 6, 7, 7);

            Vector256<int> factor2_mask_lo = Vector256.Create( 0, 0, 1, 1, 2, 2, 3, 3);
            Vector256<int> factor2_mask_hi = Vector256.Create( 4, 4, 5, 5, 6, 6, 7, 7);

            fixed (global::VerifyVectorize.Position2* position_first = position)
            fixed (global::VerifyVectorize.FloatComponent* factor_first = factor)
            fixed (global::VerifyVectorize.FloatComponent2* factor2_first = factor2)
            {
                for (; i <= end; i += 16)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* factor_ptr = (float*)(factor_first + i);
                    float* factor2_ptr = (float*)(factor2_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr + 0);
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr + 8);
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);

                    Vector256<float> factor_scalar_01 = Avx.LoadVector256(factor_ptr);
                    Vector256<float> factor_scalar_23 = Avx.LoadVector256(factor_ptr + 8);
                    Vector256<float> factor_0 = Avx2.PermuteVar8x32(factor_scalar_01, factor_mask_lo);
                    Vector256<float> factor_1 = Avx2.PermuteVar8x32(factor_scalar_01, factor_mask_hi);
                    Vector256<float> factor_2 = Avx2.PermuteVar8x32(factor_scalar_23, factor_mask_lo);
                    Vector256<float> factor_3 = Avx2.PermuteVar8x32(factor_scalar_23, factor_mask_hi);

                    Vector256<float> factor2_scalar_01 = Avx.LoadVector256(factor2_ptr);
                    Vector256<float> factor2_scalar_23 = Avx.LoadVector256(factor2_ptr + 8);
                    Vector256<float> factor2_0 = Avx2.PermuteVar8x32(factor2_scalar_01, factor2_mask_lo);
                    Vector256<float> factor2_1 = Avx2.PermuteVar8x32(factor2_scalar_01, factor2_mask_hi);
                    Vector256<float> factor2_2 = Avx2.PermuteVar8x32(factor2_scalar_23, factor2_mask_lo);
                    Vector256<float> factor2_3 = Avx2.PermuteVar8x32(factor2_scalar_23, factor2_mask_hi);

                    // --- 2. Compute
                    factor_0 = factor2_0;
                    factor_1 = factor2_1;
                    factor_2 = factor2_2;
                    factor_3 = factor2_3;

                    // --- 3. Store
                    Avx.Store(factor_ptr + 0, factor_0);
                    Avx.Store(factor_ptr + 8, factor_1);
                    Avx.Store(factor_ptr + 16, factor_2);
                    Avx.Store(factor_ptr + 24, factor_3);
                }
            }
            return i;
        }

    #endregion
    }
}
