//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, ref Position1 position, float deltaTime, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var velocitySpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(ref position, velocitySpan, deltaTime);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(ref position, in velocitySpan[n], deltaTime);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Velocity1>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Velocity1>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Velocity1>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(ref 
            Position1 position,
            Span<global::VerifyVectorize.Velocity1> velocity,
            float deltaTime)
        {
            int i = 0;
            var end = velocity.Length - 8;
            if (i > end) {
                return 0;
            }
            Vector128<float> position_0 = Vector128.Create(position);
            Vector256<int> velocity_mask_0 = Vector256.Create( 0, 1, 2, 3, 4, 5, 6, 7);
            var deltaTime_scalar = Vector256.Create(deltaTime);

            fixed (global::VerifyVectorize.Velocity1* velocity_first = velocity)
            {
                for (; i <= end; i += 8)
                {
                    float* velocity_ptr = (float*)(velocity_first + i);

                    // 1. Load
                    Vector256<float> velocity_scalar = Avx.LoadVector256(velocity_ptr);
                    Vector256<float> velocity_0 = Avx2.PermuteVar8x32(velocity_scalar, velocity_mask_0);

                    // 2. Compute
                    position_0 = Fma.MultiplyAdd(velocity_0, deltaTime_scalar, position_0);

                    // 3. Store
                    Avx.Store(position_ptr + 0, position_0);


                }
            }
            return i;
        }

    #endregion
    }
}
