using Friflo.Engine.ECS;
using NUnit.Framework;
using Tests.ECS;
using Tests.Utils;
using static NUnit.Framework.Assert;



partial class TestClass
{
    [Query]
    [AllComponents<MyComponent1>]
    [AnyComponents<MyComponent2>]
    [WithoutAllComponents<MyComponent3>]
    [WithoutAnyComponents<MyComponent4>]
    [AllTags<TestTag>]
    [AnyTags<TestTag2>]
    [WithoutAllTags<TestTag3>]
    [WithoutAnyTags<TestTag4>]
    public static void MovePosition(ref Position position) {
        position.x += 1;
    }
    
#region will be generated
    private static readonly int MovePositionSlot_ = EntityStore.UserDataNewSlot();
    
    /// <summary>Query method generated by <see cref="MovePosition"/>.</summary>
    /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
    public static ArchetypeQuery MovePositionQuery_(EntityStore store)
    {
         var query = (ArchetypeQuery<Position>)store.UserDataGet(MovePositionSlot_);
         if (query == null) {
             query = store.Query<Position>();
             store.UserDataSet(MovePositionSlot_, query);
         }
         foreach (var chunk in query.Chunks)
         {
             var entities = chunk.Entities;
             var componentsSpan = chunk.Chunk1.Span;
             for (int n = 0; n < entities.Length; n++) {
                 MovePosition(ref componentsSpan[n]);
             }
         }
         return query;
    }
    #endregion
}


// ReSharper disable InconsistentNaming
namespace Tests.ECS.Base {

public static class Test_SrcGen
{
    [Test]
    public static void Test_SrcGen_Call() {
        var store = new EntityStore();
        var entity = store.CreateEntity(new Position());
        
        TestClass.MovePositionQuery_(store);
        AreEqual(1.0f, entity.GetComponent<Position>().x);
        
        var start = Mem.GetAllocatedBytes();
        TestClass.MovePositionQuery_(store);
        Mem.AssertNoAlloc(start);
        AreEqual(2.0f, entity.GetComponent<Position>().x);
    }
}

}

