using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Friflo.Engine.ECS.Generators;

[Generator]
public class AttributeQueryGenerator : IIncrementalGenerator
{
    // --- IIncrementalGenerator
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#if DEBUG_XXX
        if (!System.Diagnostics.Debugger.IsAttached)
        {
            System.Diagnostics.Debugger.Launch();
        }
#endif
        // Filter for methods with the attribute
        var methodDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Friflo.Engine.ECS.QueryAttribute",
            predicate: (node, _) => node is MethodDeclarationSyntax,
            transform: (ctx, _) => ctx
        );

        // Generate the source
        context.RegisterSourceOutput(methodDeclarations, (spc, ctx) =>
        {
            // Get the symbol for the interfaces; ITag and IComponent
            var compilation = ctx.SemanticModel.Compilation;
            var types = new EcsTypes {
                componentInterface  = compilation.GetTypeByMetadataName("Friflo.Engine.ECS.IComponent"),
                entityStruct        = compilation.GetTypeByMetadataName("Friflo.Engine.ECS.Entity"),
                vectorizeAttribute  = compilation.GetTypeByMetadataName("Friflo.Engine.ECS.VectorizeAttribute"),
            };
            var methodSymbol        = (IMethodSymbol)ctx.TargetSymbol;
            var className           = methodSymbol.ContainingType.ToDisplayString(ClassNameFormat);
            var methodName          = methodSymbol.Name;
            var isGlobalNamespace   = methodSymbol.ContainingNamespace.IsGlobalNamespace;
            var namespaceName       = methodSymbol.ContainingType.ContainingNamespace.ToDisplayString();
            var attributes          = methodSymbol.GetAttributes();
            var attributeCode       = EmitFilters(attributes);
            var methodSignature     = methodSymbol!.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat);
            var parameters          = methodSymbol.Parameters;
            var components          = GetComponents(parameters, types);
            // made required static symbols unique to prevent duplicate symbol names
            var hash = "_" + Utils.GetMd5Hash(methodSignature).Substring(0, 4); // 8 chars is usually enough
            var query = new Query {
                methodSymbol    = methodSymbol,
                attributes      = attributes,
                components      = components,
                hash            = hash,
                ecsTypes        = types
            };
            var componentArgs       = EmitComponentArgs(components);
            var chunkVariables      = EmitChunkVariables(components);
            var lambdaParameters    = EmitLambdaParameters(parameters, types);
            var vectorizeCode       = Vectorizer.Emit(query);

            var source = $@"// <auto-generated/>
using System;
using System.ComponentModel;
using Friflo.Engine.ECS;

{(isGlobalNamespace ? "" : $"namespace {namespaceName}\r\n{{")}
    public partial class {className}
    {{
        /// <summary>Query method generated for: <see cref=""{methodName}""/>.</summary>
        /// <returns>The executed <see cref=""ArchetypeQuery""/> for debugging purposes</returns>
        public {(methodSymbol.IsStatic ? "static " : "")}ArchetypeQuery {methodName}Query({EmitMethodSignature(parameters, types)})
        {{
            var _query = _{methodName}_GetQuery{hash}(_store);
            foreach (var chunk in _query.Chunks)
            {{
                var _entities = chunk.Entities;
{chunkVariables}
                for (int n = 0; n < _entities.Length; n++) {{
                    {methodName}({lambdaParameters});
                }}
            }}
            return _query;
        }}

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _{methodName}_Slot{hash} = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<{componentArgs}> _{methodName}_GetQuery{hash}(EntityStore _store)
        {{
            var _query = (ArchetypeQuery<{componentArgs}>)EntityStore.UserDataGet(_store, _{methodName}_Slot{hash});
            if (_query != null) {{
                return _query;
            }}
            _query = _store.Query<{componentArgs}>();
{attributeCode}
            EntityStore.UserDataSet(_store, _{methodName}_Slot{hash}, _query);
            return _query;
        }}
{query.avxMethod}
    #endregion
    }}
{(isGlobalNamespace ? "" : "}")}
";
            var fileName =
                methodSymbol!.ContainingType.ToDisplayString().Replace('<', '{').Replace('>', '}') + "/" +
                methodSymbol!.ToDisplayString(FullNameFormat).Replace('<', '{').Replace('>', '}');
            // using hash instead of method signature for file name. Signature would lead to long file names not supported by the OS
            spc.AddSource($"{fileName}{hash}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
    
    private static readonly SymbolDisplayFormat ClassNameFormat = new SymbolDisplayFormat(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters
    );
    private static readonly SymbolDisplayFormat FullNameFormat = new SymbolDisplayFormat(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameOnly,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        // memberOptions: SymbolDisplayMemberOptions.IncludeContainingType,
        parameterOptions: SymbolDisplayParameterOptions.IncludeType // Include this if you want (string x, int y)
    );
    
    private static string EmitMethodSignature(ImmutableArray<IParameterSymbol> parameters, EcsTypes ecsTypes)
    {
        var sb = new StringBuilder();
        sb.Append("EntityStore _store");
        foreach (var parameter in parameters) {
            bool isComponent = parameter.Type.AllInterfaces.Contains(ecsTypes.componentInterface);
            if (isComponent) {
                continue;
            }
            bool isEntity = parameter.Name == "entity" && SymbolEqualityComparer.Default.Equals(parameter.Type, ecsTypes.entityStruct);
            if (isEntity) {
                continue;
            }
            sb.Append(", ");
            AppendRefKind(sb, parameter.RefKind);
            string type = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append(type);
            sb.Append(" ");
            sb.Append(parameter.Name);
        }
        return sb.ToString();
    }
    
    private static string EmitComponentArgs(List<IParameterSymbol> components)
    {
        var sb = new StringBuilder();
        foreach (var component in components) {
            if (sb.Length > 0) {
                sb.Append(", ");
            }
            string type = component.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append(type);
        }
        return sb.ToString();
    }
    
    private static string EmitChunkVariables(List<IParameterSymbol> components)
    {
        var sb = new StringBuilder();
        var index = 1;
        foreach (var component in components) {
            // e.g. var componentSpan = chunk.Chunk1.Span;
            if (sb.Length > 0) {
                sb.AppendLine("");
            }
            sb.Append("                var ");
            sb.Append(component.Name);
            sb.Append("Span = chunk.Chunk");
            sb.Append(index++);
            sb.Append(".Span;");
        }
        return sb.ToString();
    }
    
    private static string EmitLambdaParameters(ImmutableArray<IParameterSymbol> parameters, EcsTypes ecsTypes)
    {
        var sb = new StringBuilder();
        foreach (var parameter in parameters) {
            if (sb.Length > 0) {
                sb.Append(", ");
            }
            bool isComponent = parameter.Type.AllInterfaces.Contains(ecsTypes.componentInterface);
            if (isComponent) {
                AppendRefKind(sb, parameter.RefKind);
                sb.Append(parameter.Name);
                sb.Append("Span[n]");
                continue;
            }
            bool isEntity = parameter.Name == "entity" && SymbolEqualityComparer.Default.Equals(parameter.Type, ecsTypes.entityStruct);
            if (isEntity) {
                sb.Append("_entities.EntityAt(n)");
                continue;
            }
            AppendRefKind(sb, parameter.RefKind);
            sb.Append(parameter.Name);
        }
        return sb.ToString();
    }
    
    private static List<IParameterSymbol> GetComponents(ImmutableArray<IParameterSymbol> parameters, EcsTypes ecsTypes)
    {
        var result = new List<IParameterSymbol>();
        foreach (var parameter in parameters)
        {
            bool isComponent = parameter.Type.AllInterfaces.Contains(ecsTypes.componentInterface);
            if (isComponent) {
                result.Add(parameter);   
            }
        }
        return result;
    }

    private static void AppendRefKind(StringBuilder sb, RefKind refKind)
    {
        switch (refKind) {
            case RefKind.Ref:
                sb.Append("ref ");
                break;
            case RefKind.In:
                sb.Append("in ");
                break;
            case RefKind.Out:
                sb.Append("out ");
                break;
        }
    }
    
    private static string EmitFilters(ImmutableArray<AttributeData> attributes)
    {
        var sb = new StringBuilder();
        foreach (var attribute in attributes) {
            INamedTypeSymbol attributeClass = attribute.AttributeClass;
            if (attributeClass == null) {
                continue;
            }
            string ns = attributeClass.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted));
            if (ns == null || ns != "Friflo.Engine.ECS") {
                continue;
            }
            switch (attributeClass.Name) {
                case "AllComponentsAttribute":
                case "AnyComponentsAttribute":
                case "WithoutAllComponentsAttribute":
                case "WithoutAnyComponentsAttribute":
                    var name = attributeClass.Name.Substring(0, attributeClass.Name.Length - "Attribute".Length);
                    var args = Utils.GetGenericTypeArguments(attributeClass);
                    sb.AppendLine($"            _query.{name}(ComponentTypes.Get<{args}>());");
                    break;
                case "AllTagsAttribute":
                case "AnyTagsAttribute":
                case "WithoutAllTagsAttribute":
                case "WithoutAnyTagsAttribute":
                    name = attributeClass.Name.Substring(0, attributeClass.Name.Length - "Attribute".Length);
                    args = Utils.GetGenericTypeArguments(attributeClass);
                    sb.AppendLine($"            _query.{name}(Tags.Get<{args}>());");
                    break;
            }
        }
        return sb.ToString();
    }
}

