using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class AttributeQueryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#if DEBUG_XXX
        if (!System.Diagnostics.Debugger.IsAttached)
        {
            System.Diagnostics.Debugger.Launch();
        }
#endif
        // 1. Filter for methods with the attribute
        var methodDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Friflo.Engine.ECS.QueryAttribute",
            predicate: (node, _) => node is MethodDeclarationSyntax,
            transform: (ctx, _) => ctx
        );

        // 2. Generate the source
        context.RegisterSourceOutput(methodDeclarations, (spc, context) =>
        {
            var methodSymbol = (IMethodSymbol)context.TargetSymbol;
            var className = methodSymbol.ContainingType.Name;
            var methodName = methodSymbol.Name;
            var isGlobalNamespace = methodSymbol.ContainingNamespace.IsGlobalNamespace;
            var namespaceName = methodSymbol.ContainingType.ContainingNamespace.ToDisplayString();

            var source = $@"// <auto-generated/>
using System;

{(isGlobalNamespace ? "" : $"namespace {namespaceName} {{")}
    public partial class {className}
    {{
        /// <summary>
        /// Query method generated by <see cref=""{methodName}""/>. 
        /// </summary>
        public void {methodName}Query() 
        {{
            // Console.WriteLine(""Executing {methodName} at "" + DateTime.Now);
            this.{methodName}(); // Call the original method
        }}
    }}
{(isGlobalNamespace ? "" : "}")}
";
            spc.AddSource($"{className}_{methodName}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
    
}