using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class AttributeQueryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#if DEBUG_XXX
        if (!System.Diagnostics.Debugger.IsAttached)
        {
            System.Diagnostics.Debugger.Launch();
        }
#endif
        // Filter for methods with the attribute
        var methodDeclarations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Friflo.Engine.ECS.QueryAttribute",
            predicate: (node, _) => node is MethodDeclarationSyntax,
            transform: (ctx, _) => ctx
        );

        // Generate the source
        context.RegisterSourceOutput(methodDeclarations, (spc, context) =>
        {
            // Get the symbol for the interfaces; ITag and IComponent
            INamedTypeSymbol? componentInterface = context.SemanticModel.Compilation.GetTypeByMetadataName("Friflo.Engine.ECS.IComponent");
            var methodSymbol = (IMethodSymbol)context.TargetSymbol;
            var className = methodSymbol.ContainingType.Name;
            var methodName = methodSymbol.Name;
            var isGlobalNamespace = methodSymbol.ContainingNamespace.IsGlobalNamespace;
            var namespaceName = methodSymbol.ContainingType.ContainingNamespace.ToDisplayString();
            var attributes = methodSymbol.GetAttributes();
            var parameters = methodSymbol.Parameters;
            var components = GetComponents(parameters, componentInterface);
            var componentArgs = EmitComponentArgs(components);
            var lambdaParameters =  EmitLambdaParameters(parameters, componentInterface);

            var source = $@"// <auto-generated/>
using System;
using Friflo.Engine.ECS;

{(isGlobalNamespace ? "" : $"namespace {namespaceName}\r\n{{")}
    public partial class {className}
    {{
        private static readonly int {methodName}Slot = EntityStore.UserDataNewSlot();

        /// <summary>Query method generated by <see cref=""{methodName}""/>.</summary>
        /// <returns>The executed <see cref=""ArchetypeQuery""/> for debugging purposes</returns>
        public ArchetypeQuery {methodName}Query({EmitMethodSignature(parameters, componentInterface)})
        {{
            var query = (ArchetypeQuery<{componentArgs}>)store.UserDataGet({methodName}Slot);
            if (query == null) {{
                query = store.Query<{componentArgs}>();
                store.UserDataSet({methodName}Slot, query);
            }}
            foreach (var chunk in query.Chunks)
            {{
                var entities = chunk.Entities;
                var componentSpan = chunk.Chunk1.Span;
                for (int n = 0; n < entities.Length; n++) {{
                    {methodName}({lambdaParameters});
                }}
            }}
            return query;
        }}
    }}
{(isGlobalNamespace ? "" : "}")}
";
            spc.AddSource($"{className}_{methodName}.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }
    
    private static string EmitMethodSignature(ImmutableArray<IParameterSymbol> parameters, INamedTypeSymbol? componentInterface)
    {
        var sb = new StringBuilder();
        sb.Append("EntityStore store");
        foreach (var parameter in parameters) {
            bool isComponent = parameter.Type.AllInterfaces.Contains(componentInterface);
            if (isComponent) {
                continue;
            }
            sb.Append(", ");
            string type = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append(type);
            sb.Append(" ");
            sb.Append(parameter.Name);
        }
        return sb.ToString();
    }
    
    private static string EmitComponentArgs(List<IParameterSymbol> components)
    {
        var sb = new StringBuilder();
        foreach (var component in components) {
            if (sb.Length > 0) {
                sb.Append(", ");
            }
            string type = component.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append(type);
        }
        return sb.ToString();
    }
    
    private static string EmitLambdaParameters(ImmutableArray<IParameterSymbol> parameters, INamedTypeSymbol? componentInterface)
    {
        return "ref componentSpan[n]";
        var sb = new StringBuilder();
        foreach (var parameter in parameters) {
            if (sb.Length > 0) {
                sb.Append(", ");
            }
            bool isComponent = parameter.Type.AllInterfaces.Contains(componentInterface);
            if (isComponent) {
                sb.Append("ref ");
                sb.Append(parameter.Name);
                sb.Append("Span[n]");
                continue;
            }
            /* sb.Append(", ");
            string type = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.Append(type);
            sb.Append(" ");
            sb.Append(parameter.Name);*/
        }
        return sb.ToString();
    }
    
    private static List<IParameterSymbol> GetComponents(ImmutableArray<IParameterSymbol> parameters, INamedTypeSymbol? componentInterface)
    {
        var result = new List<IParameterSymbol>();
        foreach (var parameter in parameters)
        {
            bool isComponent = parameter.Type.AllInterfaces.Contains(componentInterface);
            if (isComponent) {
                result.Add(parameter);   
            }
        }
        return result;
    }
    
}