using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MySourceGenerator
{
    [Generator]
    public class HelloGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. Filter for classes that should trigger the generation
            // For simplicity, we'll just look for any class named 'Greeter'
            var classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax { Identifier: { Text: "Greeter" } },
                    transform: (ctx, _) => ctx.Node)
                .Where(m => m is not null);

            // 2. Register the source output
            context.RegisterSourceOutput(classDeclarations, (spc, source) =>
            {
                var sourceCode = @"// <auto-generated/>
namespace GeneratedCode
{
    public partial class Greeter
    {
        public void Hello() => System.Console.WriteLine(""Hello from the Source Generator!"");
    }
}";
                spc.AddSource("Greeter.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            });
        }
    }
}