using System;
using System.Diagnostics;
using Friflo.Engine.ECS;
using NUnit.Framework;
using Tests.ECS;
using Tests.Utils;



partial class TestClass
{
    [Query]
    [AllComponents<MyComponent1>]
    [AnyComponents<MyComponent2>]
    [WithoutAllComponents<MyComponent3>]
    [WithoutAnyComponents<MyComponent4>]
    [AllTags<TestTag>]
    [AnyTags<TestTag2>]
    [WithoutAllTags<TestTag3>]
    [WithoutAnyTags<TestTag4>]
    private static void MovePosition(ref Position position) {
        position.x += 1;
    }
    
#region will be generated
    private static readonly int MovePositionSlot2 = EntityStore.UserDataNewSlot();
    
    /// <summary>Query method generated by <see cref="MovePosition"/>.</summary>
    /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
    public static ArchetypeQuery MovePositionQuery_(EntityStore store)
    {
         var query = MovePosition_GetQuery(store);
         foreach (var chunk in query.Chunks)
         {
             var entities = chunk.Entities;
             var positionSpan = chunk.Chunk1.Span;
             for (int n = 0; n < entities.Length; n++) {
                 MovePosition(ref positionSpan[n]);
             }
         }
         return query;
    }
    
    private static ArchetypeQuery<Position> MovePosition_GetQuery(EntityStore store)
    {
        var query = (ArchetypeQuery<Position>)EntityStore.UserDataGet(store, MovePositionSlot2);
        if (query != null) {
            return query;
        }
        query = store.Query<Position>();
        query.AllComponents(ComponentTypes.Get<MyComponent1>());
        
        EntityStore.UserDataSet(store, MovePositionSlot2, query);
        return query;
    }
    #endregion
}


// ReSharper disable InconsistentNaming
namespace Tests.Generators.Query {

public static class Test_Query_Lab
{
    [Test]
    public static void Test_SrcGen_Call() {
        var store = new EntityStore();
        var entity = store.CreateEntity(new Position(), new MyComponent1());
        
        TestClass.MovePositionQuery_(store);
        Assert.That(entity.GetComponent<Position>().x, Is.EqualTo(1.0f));
        
        var start = Mem.GetAllocatedBytes();
        TestClass.MovePositionQuery_(store);
        Mem.AssertNoAlloc(start);
        Assert.That(entity.GetComponent<Position>().x, Is.EqualTo(2.0f));
    }
    
    // [Test]
    public static void Test_SrcGen_perf() {
        var store = new EntityStore();
        for (int n = 0; n < 100_000; n++) {
            store.CreateEntity(new Position(), new MyComponent1());
        }
        var sw = new Stopwatch();
        sw.Start();
        for (int i = 0; i < 50_000; i++) {
            TestClass.MovePositionQuery_(store);    
        }
        Console.WriteLine($"Test_SrcGen_perf - duration: {sw.ElapsedMilliseconds} ms");
    }
}

}

