using System;
using System.Diagnostics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS;
using NUnit.Framework;
using Tests.ECS;
using Tests.Utils;

// ReSharper disable InconsistentNaming
partial class TestClass
{
    [Query]
    [AllComponents<MyComponent1>]
    [AnyComponents<MyComponent2>]
    [WithoutAllComponents<MyComponent3>]
    [WithoutAnyComponents<MyComponent4>]
    [AllTags<TestTag>]
    [AnyTags<TestTag2>]
    [WithoutAllTags<TestTag3>]
    [WithoutAnyTags<TestTag4>]
    private static void MovePosition(ref Position position) {
        position.x += 1;
    }
    
#region will be generated
    private static readonly int MovePositionSlot2 = EntityStore.UserDataNewSlot();
    
    /// <summary>Query method generated by <see cref="MovePosition"/>.</summary>
    /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
    public static ArchetypeQuery MovePositionQuery_(EntityStore store, bool vectorize)
    {
        var query = MovePosition_GetQuery(store);
        foreach (var chunk in query.Chunks)
        {
            var entities = chunk.Entities;
            var positionSpan = chunk.Chunk1.Span;
            int n = 0;
            if (!vectorize) goto Remainder;
            if (Avx.IsSupported) {
                n = MovePosition_Avx(positionSpan);
            }
        Remainder:
            for (; n < entities.Length; n++) {
                MovePosition(ref positionSpan[n]);
            }
        }
        return query;
    }
    
    private static ArchetypeQuery<Position> MovePosition_GetQuery(EntityStore store)
    {
        var query = (ArchetypeQuery<Position>)EntityStore.UserDataGet(store, MovePositionSlot2);
        if (query != null) {
            return query;
        }
        query = store.Query<Position>();
        query.AllComponents(ComponentTypes.Get<MyComponent1>());
        
        EntityStore.UserDataSet(store, MovePositionSlot2, query);
        return query;
    }
    
    private static unsafe int MovePosition_Avx(Span<Position> position)
    {
        int i = 0;
        var end = position.Length - 8;
        fixed (Position* position_ptr = position)
        {
            // We iterate in steps of 8 (8 * Vector3 = 24 floats = 3 * 256-bit registers)
            for (; i <= end; i += 8)
            {
                float* position_ptr_scalar = (float*)(position_ptr + i);

                // 1. LOAD: 3 registers filled with interleaved XYZ data
                Vector256<float> position_0 = Avx.LoadVector256(position_ptr_scalar);      // [X0 Y0 Z0 X1 Y1 Z1 X2 Y2]
                Vector256<float> position_1 = Avx.LoadVector256(position_ptr_scalar + 8);  // [Z2 X3 Y3 Z3 X4 Y4 Z4 X5]
                Vector256<float> position_2 = Avx.LoadVector256(position_ptr_scalar + 16); // [Y5 Z5 X6 Y6 Z6 X7 Y7 Z7]
                
                // 2. COMPUTE: Directly in the interleaved state!
                position_0 = Avx.Add(position_0, Vector256.Create(1f));
                position_1 = Avx.Add(position_1, Vector256.Create(1f));
                position_2 = Avx.Add(position_2, Vector256.Create(1f));

                // 3. STORE: 3 fast block writes
                Avx.Store(position_ptr_scalar, position_0);
                Avx.Store(position_ptr_scalar + 8, position_1);
                Avx.Store(position_ptr_scalar + 16, position_2);
            }
        }
        return i;
    }
    #endregion
}


// ReSharper disable InconsistentNaming
namespace Tests.Generators.Query {

public static class Test_Query_Lab
{
    [Test]
    public static void Test_SrcGen_Call() {
        var store = new EntityStore();
        var entity = store.CreateEntity(new Position(), new MyComponent1());
        
        TestClass.MovePositionQuery_(store, false);
        Assert.That(entity.GetComponent<Position>().x, Is.EqualTo(1.0f));
        
        var start = Mem.GetAllocatedBytes();
        TestClass.MovePositionQuery_(store, false);
        Mem.AssertNoAlloc(start);
        Assert.That(entity.GetComponent<Position>().x, Is.EqualTo(2.0f));
    }
    
    [Test]
    public static void Test_SrcGen_Call_Avx() {
        var store = new EntityStore();
        var entities = new Entity[100];
        for (int n = 0; n < 100; n++) {
            entities[n] = store.CreateEntity(new Position(n,0,0), new MyComponent1());
        }
        TestClass.MovePositionQuery_(store, true);
        for (int i = 0; i < 100; i++) {
            Assert.That(entities[i].GetComponent<Position>().x, Is.EqualTo(i + 1));
        }
    }
    
    // [Test]
    public static void Test_SrcGen_perf() {
        var store = new EntityStore();
        for (int n = 0; n < 100_000; n++) {
            store.CreateEntity(new Position(), new MyComponent1());
        }
        var sw = new Stopwatch();
        sw.Start();
        for (int i = 0; i < 50_000; i++) {
            TestClass.MovePositionQuery_(store, false);    
        }
        Console.WriteLine($"Test_SrcGen_perf - duration: {sw.ElapsedMilliseconds} ms");
    }
}

}

