//HintName: VerifyVectorize.MyExample/AssignConst.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignConst"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignConstQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _AssignConst_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignConst_Avx(positionSpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignConst(ref positionSpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignConst_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position1>
            _AssignConst_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position1>)
                EntityStore.UserDataGet(_store, _AssignConst_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position1>();

            EntityStore.UserDataSet(_store, _AssignConst_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignConst_Avx(
            Span<global::VerifyVectorize.Position1> position)
        {
            int i = 0;
            var end = position.Length - 32;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            // --- Locals
            var const0_scalar = Vector256.Create<float>(1); // literal

            fixed (global::VerifyVectorize.Position1* position_first = position)
            {
                for (; i <= end; i += 32)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Position1
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Position1
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Position1
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Position1

                    // --- 2. Compute
                    // position.value = 1;
                    position_0 = const0_scalar;
                    position_1 = const0_scalar;
                    position_2 = const0_scalar;
                    position_3 = const0_scalar;

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
