//HintName: VerifyVectorize.MyExample/Multiply_Matrix4x4.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Multiply_Matrix4x4"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery Multiply_Matrix4x4Query(EntityStore _store, in global::System.Numerics.Matrix4x4 transform, bool vectorized = true)
        {
            var _query = _Multiply_Matrix4x4_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Multiply_Matrix4x4_Avx(positionSpan, in transform);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Multiply_Matrix4x4(ref positionSpan[n], in transform);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Multiply_Matrix4x4_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position4>
            _Multiply_Matrix4x4_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position4>)
                EntityStore.UserDataGet(_store, _Multiply_Matrix4x4_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position4>();

            EntityStore.UserDataSet(_store, _Multiply_Matrix4x4_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _Multiply_Matrix4x4_Avx(
            Span<global::VerifyVectorize.Position4> position,
            in global::System.Numerics.Matrix4x4 transform)
        {
            int i = 0;
            var end = position.Length - 8;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            // --- Locals
            // Load Matrix columns into 256-bit registers (each column duplicated)
            // [Col0.x, Col0.y, Col0.z, Col0.w, Col0.x, Col0.y, Col0.z, Col0.w]
            Vector256<float> transform_0 = Vector256.Create(transform.M11, transform.M12, transform.M13, transform.M14, transform.M11, transform.M12, transform.M13, transform.M14);
            Vector256<float> transform_1 = Vector256.Create(transform.M21, transform.M22, transform.M23, transform.M24, transform.M21, transform.M22, transform.M23, transform.M24);
            Vector256<float> transform_2 = Vector256.Create(transform.M31, transform.M32, transform.M33, transform.M34, transform.M31, transform.M32, transform.M33, transform.M34);
            Vector256<float> transform_3 = Vector256.Create(transform.M41, transform.M42, transform.M43, transform.M44, transform.M41, transform.M42, transform.M43, transform.M44);

            fixed (global::VerifyVectorize.Position4* position_first = position)
            {
                for (; i <= end; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position4
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position4
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position4
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);   // Position4

                    // --- 2. Compute
                    // position.value = Vector4.Transform(position.value, transform);
                    position_0 = AvxUtils.TransformVector4PairAVX(position_0, transform_0, transform_1, transform_2, transform_3);
                    position_1 = AvxUtils.TransformVector4PairAVX(position_1, transform_0, transform_1, transform_2, transform_3);
                    position_2 = AvxUtils.TransformVector4PairAVX(position_2, transform_0, transform_1, transform_2, transform_3);
                    position_3 = AvxUtils.TransformVector4PairAVX(position_3, transform_0, transform_1, transform_2, transform_3);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
