//HintName: VerifyVectorize.MyExample/OperationUnsupportedError.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="OperationUnsupportedError"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public static ArchetypeQuery OperationUnsupportedErrorQuery(EntityStore _store, float value)
        {
            var _query = _OperationUnsupportedError_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var compSpan = chunk.Chunk1.Span;
                int n = 0;
                for (; n < _entities.Length; n++) {
                    OperationUnsupportedError(ref compSpan[n], value);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _OperationUnsupportedError_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position1>
            _OperationUnsupportedError_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position1>)
                EntityStore.UserDataGet(_store, _OperationUnsupportedError_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position1>();

            EntityStore.UserDataSet(_store, _OperationUnsupportedError_Slot, _query);
            return _query;
        }

    #endregion
    }
}
