//HintName: VerifyVectorize.MyExample/Cross.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Cross"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery CrossQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _Cross_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var velocitySpan = chunk.Chunk2.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Cross_Avx(positionSpan, velocitySpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Cross(ref positionSpan[n], velocitySpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Cross_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position3, global::VerifyVectorize.Velocity3>
            _Cross_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position3, global::VerifyVectorize.Velocity3>)
                EntityStore.UserDataGet(_store, _Cross_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position3, global::VerifyVectorize.Velocity3>();

            EntityStore.UserDataSet(_store, _Cross_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _Cross_Avx(
            Span<global::VerifyVectorize.Position3> position,
            Span<global::VerifyVectorize.Velocity3> velocity)
        {
            int i = 0;
            var end = position.Length - 8;
            if (i > end) {
                return 0;
            }
            // Vector layout: SoA
            fixed (global::VerifyVectorize.Position3* position_first = position)
            fixed (global::VerifyVectorize.Velocity3* velocity_first = velocity)
            {
                for (; i <= end; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* velocity_ptr = (float*)(velocity_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position3
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position3
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position3
                    (position_0, position_1, position_2) = AvxVector3.Deinterleave(position_0, position_1, position_2);

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);   // Velocity3
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);   // Velocity3
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);   // Velocity3
                    (velocity_0, velocity_1, velocity_2) = AvxVector3.Deinterleave(velocity_0, velocity_1, velocity_2);

                    // --- 2. Compute
                    // position.value = Vector3.Cross(position.value, velocity.value);
                    //   Cross arg[0]
                    Vector256<float> temp0_0 = position_0;
                    Vector256<float> temp0_1 = position_1;
                    Vector256<float> temp0_2 = position_2;

                    //   Cross arg[1]
                    Vector256<float> temp1_0 = velocity_0;
                    Vector256<float> temp1_1 = velocity_1;
                    Vector256<float> temp1_2 = velocity_2;

                    position_0 = Fma.MultiplySubtract(temp0_1, temp1_2, Avx.Multiply(temp0_2, temp1_1));
                    position_1 = Fma.MultiplySubtract(temp0_2, temp1_0, Avx.Multiply(temp0_0, temp1_2));
                    position_2 = Fma.MultiplySubtract(temp0_0, temp1_1, Avx.Multiply(temp0_1, temp1_0));

                    // --- 3. Store
                    (position_0, position_1, position_2) = AvxVector3.Interleave(position_0, position_1, position_2);
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
