//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var factorSpan = chunk.Chunk2.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(positionSpan, factorSpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(ref positionSpan[n], in factorSpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position4, global::VerifyVectorize.FloatComponent>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position4, global::VerifyVectorize.FloatComponent>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position4, global::VerifyVectorize.FloatComponent>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(
            Span<global::VerifyVectorize.Position4> position,
            Span<global::VerifyVectorize.FloatComponent> factor)
        {
            int i = 0;
            var end = position.Length - 8;
            if (i > end) {
                return 0;
            }
            // Vector layout: SoA
            // --- Locals
            Vector256<int> factor_mask_0 = Vector256.Create(0, 0, 0, 0, 1, 1, 1, 1);
            Vector256<int> factor_mask_1 = Vector256.Create(2, 2, 2, 2, 3, 3, 3, 3);
            Vector256<int> factor_mask_2 = Vector256.Create(4, 4, 4, 4, 5, 5, 5, 5);
            Vector256<int> factor_mask_3 = Vector256.Create(6, 6, 6, 6, 7, 7, 7, 7);

            fixed (global::VerifyVectorize.Position4* position_first = position)
            fixed (global::VerifyVectorize.FloatComponent* factor_first = factor)
            {
                for (; i <= end; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* factor_ptr = (float*)(factor_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position4
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position4
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position4
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);   // Position4
                    (position_0, position_1, position_2, position_3) = AvxVector4.Deinterleave(position_0, position_1, position_2, position_3);

                    Vector256<float> factor_0 = Avx.LoadVector256(factor_ptr);      // FloatComponent

                    // --- 2. Compute
                    // position.value = position.value * factor.value;
                    position_0 = Avx.Multiply(position_0, factor_0);
                    position_1 = Avx.Multiply(position_1, factor_0);
                    position_2 = Avx.Multiply(position_2, factor_0);
                    position_3 = Avx.Multiply(position_3, factor_0);

                    // --- 3. Store
                    (position_0, position_1, position_2, position_3) = AvxVector4.Interleave(position_0, position_1, position_2, position_3);
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
