//HintName: VerifyVectorize.MyExample/MoveExample.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="MoveExample"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery MoveExampleQuery(EntityStore _store, float deltaTime, bool vectorized = true)
        {
            var _query = _MoveExample_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var velocitySpan = chunk.Chunk2.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _MoveExample_Avx(positionSpan, velocitySpan, deltaTime);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    MoveExample(ref positionSpan[n], in velocitySpan[n], deltaTime);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _MoveExample_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::Friflo.Engine.ECS.Position, global::VerifyVectorize.Velocity>
            _MoveExample_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::Friflo.Engine.ECS.Position, global::VerifyVectorize.Velocity>)
                EntityStore.UserDataGet(_store, _MoveExample_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::Friflo.Engine.ECS.Position, global::VerifyVectorize.Velocity>();

            EntityStore.UserDataSet(_store, _MoveExample_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _MoveExample_Avx(
            Span<global::Friflo.Engine.ECS.Position> position,
            Span<global::VerifyVectorize.Velocity> velocity,
            float deltaTime)
        {
            int i = 0;
            var end = position.Length - 8;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            // --- Locals
            var deltaTime_scalar = Vector256.Create(deltaTime);

            fixed (global::Friflo.Engine.ECS.Position* position_first = position)
            fixed (global::VerifyVectorize.Velocity* velocity_first = velocity)
            {
                for (; i <= end; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* velocity_ptr = (float*)(velocity_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);   // Velocity
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);   // Velocity
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);   // Velocity

                    // --- 2. Compute
                    // position.value *= velocity.value * deltaTime;
                    position_0 = Avx.Multiply(position_0, Avx.Multiply(velocity_0, deltaTime_scalar));
                    position_1 = Avx.Multiply(position_1, Avx.Multiply(velocity_1, deltaTime_scalar));
                    position_2 = Avx.Multiply(position_2, Avx.Multiply(velocity_2, deltaTime_scalar));

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
