//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, global::System.Numerics.Vector3 vector, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(positionSpan, vector);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(ref positionSpan[n], vector);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::Friflo.Engine.ECS.Position>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::Friflo.Engine.ECS.Position>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::Friflo.Engine.ECS.Position>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(
            Span<global::Friflo.Engine.ECS.Position> position,
            global::System.Numerics.Vector3 vector)
        {
            int i = 0;
            var end = position.Length - 8;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            // --- Locals
            var vector_0 = Vector256.Create(vector.X, vector.Y, vector.Z, vector.X, vector.Y, vector.Z, vector.X, vector.Y);
            var vector_1 = Vector256.Create(vector.Z, vector.X, vector.Y, vector.Z, vector.X, vector.Y, vector.Z, vector.X);
            var vector_2 = Vector256.Create(vector.Y, vector.Z, vector.X, vector.Y, vector.Z, vector.X, vector.Y, vector.Z);

            fixed (global::Friflo.Engine.ECS.Position* position_first = position)
            {
                for (; i <= end; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position

                    // --- 2. Compute
                    // position.value = vector;
                    position_0 = vector_0;
                    position_1 = vector_1;
                    position_2 = vector_2;

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
