//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var vectorSpan = chunk.Chunk2.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(positionSpan, vectorSpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(ref positionSpan[n], vectorSpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position4, global::VerifyVectorize.Velocity4>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position4, global::VerifyVectorize.Velocity4>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position4, global::VerifyVectorize.Velocity4>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(
            Span<global::VerifyVectorize.Position4> position,
            Span<global::VerifyVectorize.Velocity4> vector)
        {
            int i = 0;
            var end = position.Length - 8;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            fixed (global::VerifyVectorize.Position4* position_first = position)
            fixed (global::VerifyVectorize.Velocity4* vector_first = vector)
            {
                for (; i <= end; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* vector_ptr = (float*)(vector_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position4
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position4
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position4
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);   // Position4

                    Vector256<float> vector_0 = Avx.LoadVector256(vector_ptr +  0);   // Velocity4
                    Vector256<float> vector_1 = Avx.LoadVector256(vector_ptr +  8);   // Velocity4
                    Vector256<float> vector_2 = Avx.LoadVector256(vector_ptr + 16);   // Velocity4
                    Vector256<float> vector_3 = Avx.LoadVector256(vector_ptr + 24);   // Velocity4

                    // --- 2. Compute
                    // position.value = vector;
                    position_0 = vector_0;
                    position_1 = vector_1;
                    position_2 = vector_2;
                    position_3 = vector_3;

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
