//HintName: VerifyVectorize.MyExample/InvalidComponent.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="InvalidComponent"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery InvalidComponentQuery(EntityStore _store, float value)
        {
            var _query = _InvalidComponent_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var componentSpan = chunk.Chunk1.Span;
                int n = 0;
                for (; n < _entities.Length; n++) {
                    InvalidComponent(ref componentSpan[n], value);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _InvalidComponent_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.MyComponent1>
            _InvalidComponent_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.MyComponent1>)
                EntityStore.UserDataGet(_store, _InvalidComponent_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.MyComponent1>();

            EntityStore.UserDataSet(_store, _InvalidComponent_Slot, _query);
            return _query;
        }

    #endregion
    }
}
