//HintName: VerifyVectorize.MyExample/LocalVariable.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Engine.ECS.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="LocalVariable"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery LocalVariableQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _LocalVariable_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var velocitySpan = chunk.Chunk2.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _LocalVariable_Avx(positionSpan, velocitySpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    LocalVariable(ref positionSpan[n], velocitySpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _LocalVariable_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>
            _LocalVariable_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>)
                EntityStore.UserDataGet(_store, _LocalVariable_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>();

            EntityStore.UserDataSet(_store, _LocalVariable_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _LocalVariable_Avx(
            Span<global::VerifyVectorize.Position1> position,
            Span<global::VerifyVectorize.Velocity1> velocity)
        {
            int i = 0;
            var end = position.Length - 32;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            fixed (global::VerifyVectorize.Position1* position_first = position)
            fixed (global::VerifyVectorize.Velocity1* velocity_first = velocity)
            {
                for (; i <= end; i += 32)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* velocity_ptr = (float*)(velocity_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Position1
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Position1
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Position1
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Position1

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);  // Velocity1
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);  // Velocity1
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);  // Velocity1
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24);  // Velocity1

                    // --- 2. Compute
                    // var localVar = position.value;
                    var localVar_0 = position_0;
                    var localVar_1 = position_1;
                    var localVar_2 = position_2;
                    var localVar_3 = position_3;

                    // localVar = velocity.value;
                    localVar_0 = velocity_0;
                    localVar_1 = velocity_1;
                    localVar_2 = velocity_2;
                    localVar_3 = velocity_3;

                    // position.value = localVar;
                    position_0 = localVar_0;
                    position_1 = localVar_1;
                    position_2 = localVar_2;
                    position_3 = localVar_3;

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
