//HintName: VerifyVectorize.MyExample/MethodSin.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="MethodSin"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery MethodSinQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _MethodSin_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var velocitySpan = chunk.Chunk2.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _MethodSin_Avx(positionSpan, velocitySpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    MethodSin(ref positionSpan[n], in velocitySpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _MethodSin_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>
            _MethodSin_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>)
                EntityStore.UserDataGet(_store, _MethodSin_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>();

            EntityStore.UserDataSet(_store, _MethodSin_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _MethodSin_Avx(
            Span<global::VerifyVectorize.Position1> position,
            Span<global::VerifyVectorize.Velocity1> velocity)
        {
            int i = 0;
            var end = position.Length - 32;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            fixed (global::VerifyVectorize.Position1* position_first = position)
            fixed (global::VerifyVectorize.Velocity1* velocity_first = velocity)
            {
                for (; i <= end; i += 32)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* velocity_ptr = (float*)(velocity_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Position1
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Position1
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Position1
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Position1

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);  // Velocity1
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);  // Velocity1
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);  // Velocity1
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24);  // Velocity1

                    // --- 2. Compute
                    // position.value = MathF.Sin(velocity.value);
                    position_0 = MathUtils.SinMathF(velocity_0);
                    position_1 = MathUtils.SinMathF(velocity_1);
                    position_2 = MathUtils.SinMathF(velocity_2);
                    position_3 = MathUtils.SinMathF(velocity_3);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
