//HintName: VerifyVectorize.MyExample/IncompatibleParameterTypesError.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="IncompatibleParameterTypesError"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public static ArchetypeQuery IncompatibleParameterTypesErrorQuery(EntityStore _store)
        {
            var _query = _IncompatibleParameterTypesError_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var pos1Span = chunk.Chunk1.Span;
                int n = 0;
                for (; n < _entities.Length; n++) {
                    IncompatibleParameterTypesError(ref pos1Span[n], _entities.EntityAt(n));
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _IncompatibleParameterTypesError_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position2>
            _IncompatibleParameterTypesError_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position2>)
                EntityStore.UserDataGet(_store, _IncompatibleParameterTypesError_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position2>();

            EntityStore.UserDataSet(_store, _IncompatibleParameterTypesError_Slot, _query);
            return _query;
        }

    #endregion
    }
}
