//HintName: VerifyVectorize.MyExample/Lerp.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Lerp"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery LerpQuery(EntityStore _store, global::System.Numerics.Vector3 vec, global::System.Numerics.Vector3 amount, bool vectorized = true)
        {
            var _query = _Lerp_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Lerp_Avx(positionSpan, vec, amount);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Lerp(ref positionSpan[n], vec, amount);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Lerp_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position3>
            _Lerp_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position3>)
                EntityStore.UserDataGet(_store, _Lerp_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position3>();

            EntityStore.UserDataSet(_store, _Lerp_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _Lerp_Avx(
            Span<global::VerifyVectorize.Position3> position,
            global::System.Numerics.Vector3 vec,
            global::System.Numerics.Vector3 amount)
        {
            int i = 0;
            var end = position.Length - 8;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            // --- Locals
            var vec_0 = Vector256.Create(vec.X, vec.Y, vec.Z, vec.X, vec.Y, vec.Z, vec.X, vec.Y);
            var vec_1 = Vector256.Create(vec.Z, vec.X, vec.Y, vec.Z, vec.X, vec.Y, vec.Z, vec.X);
            var vec_2 = Vector256.Create(vec.Y, vec.Z, vec.X, vec.Y, vec.Z, vec.X, vec.Y, vec.Z);

            var amount_0 = Vector256.Create(amount.X, amount.Y, amount.Z, amount.X, amount.Y, amount.Z, amount.X, amount.Y);
            var amount_1 = Vector256.Create(amount.Z, amount.X, amount.Y, amount.Z, amount.X, amount.Y, amount.Z, amount.X);
            var amount_2 = Vector256.Create(amount.Y, amount.Z, amount.X, amount.Y, amount.Z, amount.X, amount.Y, amount.Z);

            fixed (global::VerifyVectorize.Position3* position_first = position)
            {
                for (; i <= end; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position3
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position3
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position3

                    // --- 2. Compute
                    // position.value = Vector3.Lerp(position.value, vec, amount);
                    position_0 = Fma.MultiplyAdd(amount_0, Avx.Subtract(vec_0, position_0), position_0);
                    position_1 = Fma.MultiplyAdd(amount_1, Avx.Subtract(vec_1, position_1), position_1);
                    position_2 = Fma.MultiplyAdd(amount_2, Avx.Subtract(vec_2, position_2), position_2);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
