//HintName: VerifyVectorize.MyExample/MethodReciprocalSqrt.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="MethodReciprocalSqrt"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery MethodReciprocalSqrtQuery(EntityStore _store, float value, bool vectorized = true)
        {
            var _query = _MethodReciprocalSqrt_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                var velocitySpan = chunk.Chunk2.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _MethodReciprocalSqrt_Avx(positionSpan, velocitySpan, value);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    MethodReciprocalSqrt(ref positionSpan[n], in velocitySpan[n], value);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _MethodReciprocalSqrt_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>
            _MethodReciprocalSqrt_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>)
                EntityStore.UserDataGet(_store, _MethodReciprocalSqrt_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position1, global::VerifyVectorize.Velocity1>();

            EntityStore.UserDataSet(_store, _MethodReciprocalSqrt_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _MethodReciprocalSqrt_Avx(
            Span<global::VerifyVectorize.Position1> position,
            Span<global::VerifyVectorize.Velocity1> velocity,
            float value)
        {
            int i = 0;
            var end = position.Length - 32;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            // --- Locals
            var value_scalar = Vector256.Create(value);

            var const0 = Vector256.Create(0x7FFFFFFF).AsSingle(); // Abs()

            fixed (global::VerifyVectorize.Position1* position_first = position)
            fixed (global::VerifyVectorize.Velocity1* velocity_first = velocity)
            {
                for (; i <= end; i += 32)
                {
                    float* position_ptr = (float*)(position_first + i);
                    float* velocity_ptr = (float*)(velocity_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Position1
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Position1
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Position1
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Position1

                    Vector256<float> velocity_0 = Avx.LoadVector256(velocity_ptr +  0);  // Velocity1
                    Vector256<float> velocity_1 = Avx.LoadVector256(velocity_ptr +  8);  // Velocity1
                    Vector256<float> velocity_2 = Avx.LoadVector256(velocity_ptr + 16);  // Velocity1
                    Vector256<float> velocity_3 = Avx.LoadVector256(velocity_ptr + 24);  // Velocity1

                    // --- 2. Compute
                    // var abs = MathF.Abs(velocity.value);
                    var abs_0 = Avx.And(velocity_0, const0);
                    var abs_1 = Avx.And(velocity_1, const0);
                    var abs_2 = Avx.And(velocity_2, const0);
                    var abs_3 = Avx.And(velocity_3, const0);

                    // position.value = value / MathF.Sqrt(abs);
                    position_0 = Avx.Multiply(Avx.ReciprocalSqrt(abs_0), value_scalar);
                    position_1 = Avx.Multiply(Avx.ReciprocalSqrt(abs_1), value_scalar);
                    position_2 = Avx.Multiply(Avx.ReciprocalSqrt(abs_2), value_scalar);
                    position_3 = Avx.Multiply(Avx.ReciprocalSqrt(abs_3), value_scalar);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
