//HintName: VerifyVectorize.MyExample/Access_static.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="Access_static"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery Access_staticQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _Access_static_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _Access_static_Avx(positionSpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    Access_static(ref positionSpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _Access_static_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position3>
            _Access_static_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position3>)
                EntityStore.UserDataGet(_store, _Access_static_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position3>();

            EntityStore.UserDataSet(_store, _Access_static_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _Access_static_Avx(
            Span<global::VerifyVectorize.Position3> position)
        {
            int i = 0;
            var end = position.Length - 8;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            fixed (global::VerifyVectorize.Position3* position_first = position)
            {
                for (; i <= end; i += 8)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position3
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position3
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position3

                    // --- 2. Compute
                    // position.value = Vector3.Truncate(position.value);
                    position_0 = Vector256.Truncate(position_0);
                    position_1 = Vector256.Truncate(position_1);
                    position_2 = Vector256.Truncate(position_2);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                }
            }
            return i;
        }

    #endregion
    }
}
