//HintName: VerifyVectorize.MyExample/InvalidStatementError.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="InvalidStatementError"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public static ArchetypeQuery InvalidStatementErrorQuery(EntityStore _store)
        {
            var _query = _InvalidStatementError_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                for (; n < _entities.Length; n++) {
                    InvalidStatementError(ref positionSpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _InvalidStatementError_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.FloatComponent>
            _InvalidStatementError_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.FloatComponent>)
                EntityStore.UserDataGet(_store, _InvalidStatementError_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.FloatComponent>();

            EntityStore.UserDataSet(_store, _InvalidStatementError_Slot, _query);
            return _query;
        }

    #endregion
    }
}
