//HintName: VerifyVectorize.MyExample/EmptyBody.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="EmptyBody"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery EmptyBodyQuery(EntityStore _store, bool vectorized = true)
        {
            var _query = _EmptyBody_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _EmptyBody_Avx(positionSpan);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    EmptyBody(ref positionSpan[n]);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _EmptyBody_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position1>
            _EmptyBody_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position1>)
                EntityStore.UserDataGet(_store, _EmptyBody_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position1>();

            EntityStore.UserDataSet(_store, _EmptyBody_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _EmptyBody_Avx(
            Span<global::VerifyVectorize.Position1> position)
        {
            int i = 0;
            var end = position.Length - 32;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            fixed (global::VerifyVectorize.Position1* position_first = position)
            {
                for (; i <= end; i += 32)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);  // Position1
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);  // Position1
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);  // Position1
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);  // Position1

                    // --- 2. Compute

                    // --- 3. Store
                }
            }
            return i;
        }

    #endregion
    }
}
