//HintName: VerifyVectorize.MyExample/AssignVector.g.cs
// <auto-generated/>
using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using Friflo.Vectorization.Intrinsics;
using Friflo.Engine.ECS;

namespace VerifyVectorize
{
    public partial class MyExample
    {
        /// <summary>Query method generated for: <see cref="AssignVector"/>.</summary>
        /// <returns>The executed <see cref="ArchetypeQuery"/> for debugging purposes</returns>
        public ArchetypeQuery AssignVectorQuery(EntityStore _store, global::System.Numerics.Vector2 min, bool vectorized = true)
        {
            var _query = _AssignVector_GetQuery(_store);
            foreach (var chunk in _query.Chunks)
            {
                var _entities = chunk.Entities;
                var positionSpan = chunk.Chunk1.Span;
                int n = 0;
                if (!vectorized) goto EntityLoop;
                if (Avx.IsSupported) {
                    n = _AssignVector_Avx(positionSpan, min);
                }
            EntityLoop:
                for (; n < _entities.Length; n++) {
                    AssignVector(ref positionSpan[n], min);
                }
            }
            return _query;
        }

    #region private members
        [EditorBrowsable(EditorBrowsableState.Never)]
        private static readonly int _AssignVector_Slot = EntityStore.UserDataNewSlot();

        [EditorBrowsable(EditorBrowsableState.Never)]
        private static ArchetypeQuery<global::VerifyVectorize.Position2>
            _AssignVector_GetQuery(EntityStore _store)
        {
            var _query = (ArchetypeQuery<global::VerifyVectorize.Position2>)
                EntityStore.UserDataGet(_store, _AssignVector_Slot);
            if (_query != null) {
                return _query;
            }
            _query = _store.Query<global::VerifyVectorize.Position2>();

            EntityStore.UserDataSet(_store, _AssignVector_Slot, _query);
            return _query;
        }

        [SkipLocalsInit]
        private static unsafe int _AssignVector_Avx(
            Span<global::VerifyVectorize.Position2> position,
            global::System.Numerics.Vector2 min)
        {
            int i = 0;
            var end = position.Length - 16;
            if (i > end) {
                return 0;
            }
            // Vector layout: AoS
            // --- Locals
            Vector128<float> min_half = Vector128.Create(min.X, min.Y, min.X, min.Y);
            var min_scalar = Avx.InsertVector128(min_half.ToVector256(), min_half, 1);

            fixed (global::VerifyVectorize.Position2* position_first = position)
            {
                for (; i <= end; i += 16)
                {
                    float* position_ptr = (float*)(position_first + i);

                    // --- 1. Load
                    Vector256<float> position_0 = Avx.LoadVector256(position_ptr +  0);   // Position2
                    Vector256<float> position_1 = Avx.LoadVector256(position_ptr +  8);   // Position2
                    Vector256<float> position_2 = Avx.LoadVector256(position_ptr + 16);   // Position2
                    Vector256<float> position_3 = Avx.LoadVector256(position_ptr + 24);   // Position2

                    // --- 2. Compute
                    // position.value = Vector2.Min(position.value, min);
                    position_0 = Avx.Min(position_0, min_scalar);
                    position_1 = Avx.Min(position_1, min_scalar);
                    position_2 = Avx.Min(position_2, min_scalar);
                    position_3 = Avx.Min(position_3, min_scalar);

                    // --- 3. Store
                    Avx.Store(position_ptr +  0, position_0);
                    Avx.Store(position_ptr +  8, position_1);
                    Avx.Store(position_ptr + 16, position_2);
                    Avx.Store(position_ptr + 24, position_3);
                }
            }
            return i;
        }

    #endregion
    }
}
